// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kshvyryaev/cyber-meower-query-service/pkg"
	"github.com/kshvyryaev/cyber-meower-query-service/pkg/controller/http"
	"github.com/kshvyryaev/cyber-meower-query-service/pkg/query"
	"github.com/kshvyryaev/cyber-meower-query-service/pkg/search"
)

// Injectors from wire.go:

func InitializeHttpServer() (*controller.HttpServer, func(), error) {
	config := pkg.ProvideConfig()
	client, err := search.ProvideElastic(config)
	if err != nil {
		return nil, nil, err
	}
	elasticMeowRepository := search.ProvideElasticMeowRepository(client)
	meowQueries := query.ProvideMeowQueries(elasticMeowRepository)
	meowController := controller.ProvideMeowController(meowQueries)
	logger, cleanup, err := pkg.ProvideZap()
	if err != nil {
		return nil, nil, err
	}
	errorHandlerMiddleware := controller.ProvideErrorHandlerMiddleware(logger)
	recoveryHandlerMiddleware := controller.ProvideRecoveryHandlerMiddleware(logger)
	httpServer := controller.ProvideHttpServer(config, meowController, errorHandlerMiddleware, recoveryHandlerMiddleware)
	return httpServer, func() {
		cleanup()
	}, nil
}
